version: "3"

services:
  backenddev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"

  frontenddev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"