version: "3"

services:
  backendprod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  frontendprod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
