version: "3"

services:
  backend:
    image: sinhala-text-genie-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  frontend:
    image: sinhala-text-genie-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
