FROM python:3.10

EXPOSE 8000

RUN mkdir build

WORKDIR /build

COPY . .
RUN pip install --no-cache-dir --upgrade -r /build/language_model/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /build/api/requirements.txt


ENV PYTHONPATH=/build


WORKDIR /build/api

CMD python -m uvicorn main:app --host 0.0.0.0 --port 8000